"""End-to-end QC tests against REAL media using REAL ffmpeg.

No mocks. These decode the fixtures and assert the measured values, which is the
property the whole project rests on: the agent's conclusion is checkable because
ffmpeg and the policy engine produce ground truth, not a plausible narrative.

Fixtures are generated by scripts/make_fixtures.sh and are gitignored; the tests
skip if they are absent.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from pipeline.policy import BLOCKED, PASS, Profile, evaluate
from pipeline.qc import run_qc

MEDIA = Path(__file__).parent.parent / "media"
PROFILE = Path(__file__).parent.parent / "pipeline" / "profiles" / "ebu_r128.yaml"

pytestmark = [
    pytest.mark.media,
    pytest.mark.skipif(
        not (MEDIA / "master_good.mp4").exists(),
        reason="fixtures missing - run scripts/make_fixtures.sh",
    ),
]


@pytest.fixture(scope="module")
def profile() -> Profile:
    return Profile.load(PROFILE)


@pytest.fixture(scope="module")
def reports(profile):
    opts = profile.black_detector_opts
    return {
        name: run_qc(MEDIA / f"{name}.mp4", black_opts=opts)
        for name in ("master_good", "master_hot", "body_black")
    }


class TestRealMeasurement:
    def test_all_fixtures_are_45s(self, reports):
        for name, rep in reports.items():
            assert rep.duration_s == pytest.approx(45.0, abs=0.05), name

    def test_good_master_measures_on_target(self, reports):
        assert reports["master_good"].loudness.integrated_lufs == pytest.approx(-23.0, abs=0.5)

    def test_hot_master_measures_hot(self, reports):
        lufs = reports["master_hot"].loudness.integrated_lufs
        assert lufs > -22.5, f"expected hot, got {lufs}"
        assert lufs == pytest.approx(-18.0, abs=1.0)

    def test_legal_black_detected_at_head_and_tail(self, reports):
        for name in ("master_good", "master_hot"):
            iv = reports[name].black_intervals
            assert len(iv) == 2, f"{name}: {iv}"
            assert iv[0].start_s == pytest.approx(0.0, abs=0.1)
            assert iv[0].end_s == pytest.approx(10.0, abs=0.2)
            assert iv[1].start_s == pytest.approx(43.0, abs=0.2)

    def test_body_black_fixture_has_an_extra_interior_interval(self, reports):
        iv = reports["body_black"].black_intervals
        assert len(iv) == 3
        mid = iv[1]
        assert mid.start_s == pytest.approx(20.0, abs=0.2)
        assert mid.duration_s == pytest.approx(2.0, abs=0.2)

    def test_body_black_fixture_audio_is_untouched(self, reports):
        """Isolates the fault: only the picture differs from master_good."""
        assert reports["body_black"].loudness.integrated_lufs == pytest.approx(
            reports["master_good"].loudness.integrated_lufs, abs=0.1
        )


class TestGateOnRealMedia:
    def test_good_master_passes(self, profile, reports):
        v = evaluate(profile, reports["master_good"])
        assert v.status == PASS, [c.message for c in v.failures]

    def test_hot_master_blocked_on_loudness_only(self, profile, reports):
        v = evaluate(profile, reports["master_hot"])
        assert v.status == BLOCKED
        assert [c.check_id for c in v.failures] == ["loudness.integrated"]

    def test_body_black_blocked_on_black_only(self, profile, reports):
        """Loudness is fine; the picture is not. The gate must not conflate them."""
        v = evaluate(profile, reports["body_black"])
        assert v.status == BLOCKED
        assert [c.check_id for c in v.failures] == ["black.body"]

    def test_mandated_head_black_never_trips_the_gate(self, profile, reports):
        """The domain correction, verified on real media."""
        for name in ("master_good", "master_hot", "body_black"):
            v = evaluate(profile, reports[name])
            assert not any(c.check_id.startswith("black.required") for c in v.failures), name
