"""House writing rules, enforced rather than requested.

A convention documented in AGENTS.md and checked by nobody is a convention that
lasts until the next contributor, human or otherwise. This is the same argument
the rest of the suite makes about validators: one with no test showing it reject
something is indistinguishable from a costume.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Named by code point rather than written literally: a test that contains the
# character it forbids would fail against itself.
EM_DASH = chr(0x2014)

# Text we own. Generated output and vendored files are not ours to restyle.
TEXT_SUFFIXES = {
    ".py",
    ".md",
    ".ts",
    ".tsx",
    ".css",
    ".yaml",
    ".yml",
    ".json",
    ".sh",
    ".txt",
    ".html",
}
EXCLUDED = {
    "requirements-lock.txt",  # generated by pip freeze
    "package-lock.json",  # generated by npm
}


def tracked_text_files() -> list[Path]:
    """Only files git tracks, so build output and venvs are excluded for free."""
    out = subprocess.run(
        ["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True
    )
    return [
        ROOT / line
        for line in out.stdout.splitlines()
        if Path(line).suffix in TEXT_SUFFIXES and Path(line).name not in EXCLUDED
    ]


def test_no_em_dashes_anywhere():
    """AGENTS.md forbids the em dash. This is what makes that true."""
    offenders = []
    for path in tracked_text_files():
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        if EM_DASH in text:
            for n, line in enumerate(text.splitlines(), 1):
                if EM_DASH in line:
                    offenders.append(f"{path.relative_to(ROOT)}:{n}")
    assert not offenders, (
        "em dash (U+2014) found; use a spaced hyphen, a comma, a colon or two "
        "sentences instead:\n  " + "\n  ".join(offenders[:20])
    )


def test_the_check_covers_the_files_that_matter():
    """A check that scans nothing passes trivially."""
    files = tracked_text_files()
    names = {p.name for p in files}
    assert len(files) > 40, f"only {len(files)} files scanned; the glob is wrong"
    for expected in ("README.md", "AGENTS.md", "GEMINI.md", "orchestrator.py"):
        assert expected in names, f"{expected} is not being checked"
